### ISSUE TITLE
Problems with non-forks

### ISSUE THREAD

**Issue by Mte90** [waseem18/Openflock#3] opened 2016-03-01 11:42 UTC
The case is strange...
That repo https://github.com/Mte90/WordPress-Plugin-Boilerplate-Powered was initially a fork and after I contact GitHub to remove as a fork.
I get that error when i try to add it:

```
Currently you cannot promote a forked repository or repository which you are not owner of! If this is not the issue, kindly contact us or raise an issue on GitHub
```

So the problem is of OpenFlock on detection or of GitHub?

**Comment by waseem18** [comment] 2016-03-01 14:36
Hey @Mte90,

It's true that you cannot promote a forked repository on Openflock. And yeah, It's not a problem from our side. It's actually a problem from GitHub. 

See here https://api.github.com/users/Mte90/repos . Can you see the repository you're speaking about in that Json data? Nope. Openflock depends on GitHub data. So it's a problem from GitHub side. 

Even I'm facing this problem now. I can't find my public repo (earlier private) in that Json data. I have reported this to GitHub. :) 

Let's see what happens...

**Comment by Mte90** [comment] 2016-03-01 15:23
So on GitHub site that repos are reported as non-forks but in the API they reported as forks.
I contact GitHub for that problem.

**Comment by waseem18** [comment] 2016-03-01 15:27
Hey @Mte90 

I found that the problem is also with Openflock. It seems paginations exists for the API Json data. I didn't know about it before and only took the details of the repos that are in the main page. Your Json data has got one more pagination and the repo. you're speaking about will be in that page. 

I'll try to resolve it soon! :+1:

**Comment by Mte90** [comment] 2016-03-01 15:28
:smile:

**Closed as completed** 2017-08-09 05:31 UTC
